name: CI
on:
  push:
    branches: [ "dev", "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          # vite 需要在node>=12 的环境下执行
          # puppeteer 需要在node>=14.1.0 的环境下执行
          node-version: '16.x'
      - name: Installing Dependencies
        run: npm install
      - name: Running Lint
        run: npm run lint
      # - name: Running Test
      #   run: npm test
  B:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: 
          echo "kayneliu is a good boy."